---
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3

# env:
#   global:
#     - secure: "<encrypted PYPI_USER=username>"
#     - secure: "<encrypted PYPI_PASS=password>"

before_install:
  - pip list
  - pip install poetry

install:
  - poetry install

script:
  - inv format --check
  - inv lint
  # - inv type-check
  - inv unit-test
  # - inv safety
  - inv coverage --report=xml
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry build

deploy:
  - provider: script
    script: poetry publish -r compendium
    skip_cleanup: true
    on:
      branch: master
      tags: true
