---
language: python
cache: pip

stages:
  - quality-assurance
  - name: deploy
    if: tag IS present
  - documentation
  - coverage

before_install:
  - pip install --upgrade pip
  - pip uninstall pipenv numpy -y
  - pip install poetry
  # XXX: yeah this VVV
  - pip install --upgrade pip

install:
  - poetry install
  - pip install xmltodict

jobs:
  fast_finish: true
  include:
    - stage: quality-assurance
      script:
        - inv qa.style --check
        - inv qa.lint
        - inv qa.unit-test
        - inv qa.static-analysis

    - stage: deploy
      script: poetry config pypi-token.pypi $PYPI_TOKEN
      before_deploy: poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true

    - stage: documentation
      script:
        - inv doc.lint
        - inv doc.test
        - inv doc.coverage
        - inv doc.build
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: site
        skip_cleanup: true
        keep_history: true
        on:
          branch: master

    - stage: coverage
      script:
        - inv qa.coverage --report=xml
        - bash <(curl -s https://codecov.io/bash)
