---
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - test
  - name: pypi-deploy
    if: tag IS present
  - coverage

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: test
      script:
        - inv format --check
        - inv lint
        - inv unit-test
        - inv safety

    - stage: pypi-deploy
      script: skip
      before_deploy:
        - poetry build
      
      deploy:
        provider: script
        script:
          - poetry config repositories.pypi 'https://pypi.org/simple/'
          - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
          - poetry publish
        skip_cleanup: true
        skip_existing: true

    - stage: coverage
      script:
        - inv coverage --report=xml
        - bash <(curl -s https://codecov.io/bash)
