---
language: python

.test_scripts: &test_scripts
  script:
    - inv format --check
    - inv lint
    - inv unit-test
    - inv safety

stages:
  - python-3.6
  - python-3.7
  - python-3.8
  - name: pypi-deploy
    if: branch = master
  - coverage

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  fast_finish: true
  include:
    - stage: python-3.6
      python: 3.6
      <<: *test_scripts

    - stage: python-3.7
      python: 3.7
      <<: *test_scripts

    - stage: python-3.8
      python: 3.8
      <<: *test_scripts

    - stage: pypi-deploy
      script: skip
      before_deploy:
        - poetry build
      
      deploy:
        - provider: script
          script:
            - poetry config repositories.pypi 'https://pypi.org/simple/'
            - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
            - poetry publish
          skip_cleanup: true

    - stage: coverage
      script:
        - inv coverage --report=xml
        - bash <(curl -s https://codecov.io/bash)
