---
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  # TODO: codex.h error :(
  # - pypy3

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

script:
  - pip list -v
  - inv format --check
  - inv lint
  # - inv type-check
  - inv unit-test
  # TODO: Environment already populated :(
  # - inv safety
  - inv coverage --report=xml
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - poetry build
  - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI

deploy:
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      branch: master
      tags: true
