---
language: python
python:
  - 3.6
  # - 3.7
  # - 3.8
  # - pypy3  # codex.h

stages:
  - testing
  - name: test-deploy
    if: branch = master AND tag IS blank

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  fast_finish: true
  include:
    - stage: testing
      python: 3.6
      script:
        - inv format --check
        - inv lint
        - inv unit-test
        - inv safety

    - stage: test-deploy
      script: skip
      before_deploy:
        - poetry config repositories.test-pypi https://test.pypi.org/legacy/
        - poetry config pypi-token.test-pypi $POETRY_PYPI_TOKEN_PYPI
        - poetry build
      deploy:
        - provider: script
          script: poetry publish --repository test-pypi
          skip_cleanup: true

before_deploy:
  - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
  - poetry build

deploy:
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      branch: master
      tags: true

after_success:
  - inv coverage --report=xml
  - bash <(curl -s https://codecov.io/bash)
