---
language: python
cache: pip
# python:
#   - "3.6"
#   - "3.7"
#   - "3.8"

stages:
  - test
  - name: deploy
    if: tag IS present
  - coverage

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  fast_finish: true
  include:
    - stage: test
      script: inv format --check
    - script: inv lint
    - script: inv unit-test
    - script: inv safety


    - stage: deploy
      script: skip
      before_deploy:
        - poetry build
        - poetry config repositories.pypi 'https://pypi.org/simple/'
        - poetry config pypi-token.pypi $PYPI_TOKEN
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true

    - stage: coverage
      script:
        - inv coverage --report=xml
        - bash <(curl -s https://codecov.io/bash)
