---
language: python
python:
  - 3.6
  # - 3.7
  # - 3.8
  # - pypy3  # codex.h

stages:
  - testing
  - name: test-deploy
    if: branch = master AND tag IS blank
  - name: deploy
    if: branch = master AND tag IS present

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: testing
      script:
        - inv format --check
        - inv lint
        - inv unit-test
        - inv safety

    - stage: test-deploy
      before_deploy:
        - poetry build
        - poetry config repositories.test-pypi https://test.pypi.org/simple/
        - poetry config pypi-token.test-pypi $POETRY_PYPI_TOKEN_PYPI
      deploy:
        - provider: script
          script: poetry publish
          skip_cleanup: true

    - stage: deploy
      before_deploy:
        - poetry build
        - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
      deploy:
        - provider: script
          script: poetry publish
          skip_cleanup: true

after_success:
  - inv coverage --report=xml
  - bash <(curl -s https://codecov.io/bash)
