---
language: python
python:
  - 3.6
  # - 3.7
  # - 3.8
  # - pypy3  # codex.h

stages:
  - quality
  - test
  - build
  - test-deploy
    if: branch = master
  - name: deploy
    if: branch = master

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: quality
      script:
        - inv format --check
        - inv lint
        # - inv type-check

    - stage: test
      script:
        - inv unit-test
        - inv safety

    - stage: build
      script:
        - poetry build 

    - stage: test-deploy
      script:
        - poetry config reposistories.test-pypi https://test.pypi.org/simple/
        - poetry config pypi-token.test-pypi $POETRY_PYPI_TOKEN_PYPI
      deploy:
        - provider: script
          script: poetry publish
          skip_cleanup: true
          on:
            tags: false

    - stage: deploy
      script:
        - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
      deploy:
        - provider: script
          script: poetry publish
          skip_cleanup: true
          on:
            tags: true

after_success:
  - inv coverage --report=xml
  - bash <(curl -s https://codecov.io/bash)
