---
site_name: Compendium

repo_url: https://github.com/kuwv/python-compendium

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      # handlers:
      #   python:
      #     rendering:
      #       show_source: false 
