---
name: MkDocs
on:
  workflow_run:
    workflows: ['CI build']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python 3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build,docs]
      - name: Lint documentation
        run: |
          python -m invoke doc.lint
          python -m invoke doc.test
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python 3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build,docs]
      - name: Perform documentation tests
        run: |
          python -m invoke doc.coverage
          python -m invoke doc.build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python 3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Lint documentation
        run: |
          python -m doctest README.md
